[project]
name = "Livt.Base"
version = "0.2.0"
path = "src"
outdir = "out"

[tests]
path = "tests"
components = [
    "BitsTest",
    "AsciiTest",
    "ConvertTest",
    "FormatTest",
    "ArrayTest",
    "DiagnosticsTest",
    "ArrayUnsizedParamTest",
    "StringTest",
    "StringHelperTest",
    "PeriodicTickProviderTest",
    "PeriodicTickProvider50MHzTest"
]

[build.debug]
warnings = ["all"]

[build.release]
warnings = ["all"]
