[project]
name = "Livt.Base"
version = "0.1.1"
path = "src"
outdir = "out"

[tests]
path = "tests"
components = [
    "BitsTest",
    "AsciiTest",
    "ConvertTest",
    "FormatTest",
    "ArrayTest",
    "DiagnosticsTest",
    "ArrayUnsizedParamTest",
    "StringTest",
    "StringHelperTest"
]

[build.debug]
warnings = ["all", "no-variable-divisor"]

[build.release]
warnings = ["all"]
