-- Copyright (C) 2026 Eccelerators GmbH
--
-- This code was generated by:
--
-- Livt Compiler v0.0.0-0000000
-- VHDL Extension for Livt v0.0.0-0000000
--
-- Further information at https://eccelerators.com/livt
--
-- Changes to this file may cause incorrect behavior and will be lost if the
-- code is regenerated.
library ieee;
	use ieee.std_logic_1164.all;
	use ieee.numeric_std.all;

use work.livt_format_format_package.all;
use work.livt_lang_icontext_package.all;
use work.livt_lang_package.all;

entity livt_format_format_slice is
port (Clk: in std_logic; Rst: in std_logic;
tostringbyte_in : in t_format_tostringbyte_in;
tostringbyte_out : out t_format_tostringbyte_out;
tostringint_in : in t_format_tostringint_in;
tostringint_out : out t_format_tostringint_out;
tostringuint_in : in t_format_tostringuint_in;
tostringuint_out : out t_format_tostringuint_out;
tohexbyte_in : in t_format_tohexbyte_in;
tohexbyte_out : out t_format_tohexbyte_out;
tobinarybyte_in : in t_format_tobinarybyte_in;
tobinarybyte_out : out t_format_tobinarybyte_out);
end;
architecture rtl of livt_format_format_slice is begin
dut: entity work.livt_format_format port map (ctor_lvt_context_in => (clk => Clk, rst => Rst, tickspersecond => to_unsigned(50000000,32), periodns => to_unsigned(20,32), hightimens => to_unsigned(10,32), lowtimens => to_unsigned(10,32)),
tostringbyte_in => tostringbyte_in,
tostringbyte_out => tostringbyte_out,
tostringint_in => tostringint_in,
tostringint_out => tostringint_out,
tostringuint_in => tostringuint_in,
tostringuint_out => tostringuint_out,
tohexbyte_in => tohexbyte_in,
tohexbyte_out => tohexbyte_out,
tobinarybyte_in => tobinarybyte_in,
tobinarybyte_out => tobinarybyte_out);
end;
